# indicar imagen base
FROM node:18

RUN npm i -g nodemon
# crear una carpeta en la cual vamos a meter el código de nuestra app. Distribución linux del container
RUN mkdir -p /home/app

#directorio raiz
WORKDIR /home/app/

#exponer un puerto para que otros contenedores se puedan conectar al contenedor
EXPOSE 5000

CMD ["nodemon", "server.js"]